import sys
import re

def read_file(filename):
	lines = []

	process_line = False

	with open(filename, 'rb') as file:
		for line in file:
			if 'ENTER Analysis Results' in line:
				process_line = True
			elif 'LEAVE Analysis Results' in line:
				process_line = False
			elif process_line:
				lines.append(line)

	return lines

def reachdef_process_quad_list(line):
	array = []
	while line.find('<') > 0:
		quad = line[line.find("<"):line.find(">")+1]
		array.append(quad)
		line = line.replace(quad, '')
		
	array.sort()

	result = ""
	for i in array:
		result += i

	return result


def reachdef_process_lines(lines):
	quads = []
	index = 0

	while len(lines) > index:
		line = lines[index]

		name = line[line.find("[", 20):line.find("]")+1]
		inMap = reachdef_process_quad_list(lines[index+1])
		outMap = reachdef_process_quad_list(lines[index+2])

		quads.append(name + "|" + inMap + "|" + outMap)

		index+=3

	quads.sort()
	return quads
	

def reachdef_comparison(lines_base, lines_log):
	quads_base = reachdef_process_lines(lines_base)
	quads_log = reachdef_process_lines(lines_log)

	if len(quads_base) == len(quads_log):
		index = 0
		while index < len(quads_base):
			qb = quads_base[index]
			ql = quads_log[index]

			if qb != ql:
				print "Results do not match. Expected " + qb + "] but found [" + ql + "]"			
				break	

			index = index + 1

		if index == len(quads_base):
			print "Results match."

	else:
		print "Results do not match. The number of quads is different."

def main():
	if len(sys.argv) != 3:
		print ""
		print "Usage: $ python compare.py base.txt log.txt"
		print "Where base.txt is the result file provided by the instructors that will serve as the base of comparison, and log.txt is the log file generated by you running your algorithm."
		print ""

		return

	lines_base = read_file(sys.argv[1])
	lines_log = read_file(sys.argv[2])

	reachdef_comparison(lines_base, lines_log)

main()